name: Docker-container-build-and-push-to-AWS-ECR
on:
  push:
    branches:
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.6'     
    - name: Docker-container-build-and-push-to-AWS-ECR
      run: |
        ./scripts/build.sh
    
