name: Deploy-S3-serverless
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install Serverless-finch plugin
      run: npm install --save serverless-finch
    - name: Serverless AWS authentication
      run: serverless config credentials --provider aws --key ${{ env.AWS_KEY }} --secret ${{ env.AWS_SECRET }}
    - name: Install NPM dependencies
      run: npm install
    - name: Deploy Serverless functions
      run: serverless client deploy --no-confirm
